package com.freshkeeper.model

data class FoodItem(
    val id: String? = null,
    val barcode: String? = null,
    val userId: String,
    val householdId: String? = null,
    val name: String,
    val expiryTimestamp: Long,
    val discardTimestamp: Long? = null,
    val quantity: Int,
    val unit: String,
    val storageLocation: String,
    val category: String,
    val consumed: Boolean,
    val thrownAway: Boolean,
    val imageId: String? = null,
    @Transient var daysDifference: Int = 0,
    val nutriments: Nutriments? = null,
    val nutriScore: String? = null,
) {
    constructor() : this(
        "",
        null,
        "",
        "",
        "",
        0L,
        0L,
        0,
        "",
        "",
        "",
        false,
        false,
        null,
        0,
        Nutriments(),
        "",
    )
}
